apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb-service.default.svc.cluster.local:8086
    database: influxdb
    basicAuth: true
    secureJsonData.basicAuthUser: root
    secureJsonData.basicAuthPassword: root
    editable: true
