apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
type: Opaque
data:
    wpdb-name: d29yZHByZXNzZGI=
    wpdb-username: d29yZHByZXNz
    wpdb-password: d29yZHByZXNz
    admin-username: cGhwbXlhZG1pbg==
    admin-password: cGhwbXlhZG1pbg==
    ftps-user: cm9vdA==
    ftps-password: UGFzc3dvcmQyMDIw
    ifdb-name: aW5mbHV4ZGI=
    ifdb-user: cm9vdA==
    ifdb-password: cm9vdA==
    nginx-user: cm9vdA==
    nginx-password: cm9vdA==
